### ISSUE TITLE
installation packages compatibility issue 

### ISSUE THREAD

**Issue by Addalin** [martin-rdz/ARLreader#7]
Hey  @ZPYin, 

Is there a specific reason for the requirement of certain version numbers of the required packages?
 
I wish to use it with an existing python env I am already running (e.g. python > 3.8). 

These are the installation steps I tried: 

```conda install altgraph atomicwrites attrs colorama Cython future importlib-metadata more-itertools packaging pefile pluggy py pyparsing pytest pywin32-ctypes six wcwidth wincertstore zipp numpy```
`pip install git+https://github.com/martin-rdz/ARLreader.git`
However, the last command failed due to dependencies. 

Then I solved it as follows: 
1. Unhighlighting the versions number written in the [requirments](https://github.com/martin-rdz/ARLreader/blob/master/requirements.txt).  E.g. `altgraph==0.16.1` ---> `altgraph # ==0.16.1`
2. `git clone https://github.com/martin-rdz/ARLreader.git ARLreader`
3. `cd ARLreader`
4. `python setup.py install`

Currently, it seems that the installation worked and it's possible to import the package.

For future users, I guess that it will be better to drop the versions number requirements (unless you find it important for package functionality) 

tnx

Adi

**Comment by ZPYin** [comment]
Hi Adi! Thanks for reporting this issue.

I tried python 3.9, and failed, as well. But it's something wrong with `numpy`. Taking into account the release date of Python 3.9, a lot of dependencies still doesn't support it yet. That's why such error appears (see [here](https://pythonspeed.com/articles/switch-python-3.9/)). Could that be the reason for your issue?

Anyway, it seems still too early to move to Python 3.9 or so for this repository...

I guess @martin-rdz setup this repo based on Python 3.6 (stable version so far). And the installation goes well under python 3.6 as I tested. So, if you only need to extract the GDAS1 profile, you can try it in a separated virtual environment with python 3.6. And then switch to your normal data analysis. Could that be an option for you?

Best!!!

**Comment by Addalin** [comment]
Thank you both for answering me back.
So, for the version I am using, Python 3.8.6, the package is working (see
the workaround I mentioned above)
I didn't test it yet on 3.9.

Adi

**Comment by ZPYin** [comment]
Same issue with installing numpy with python 3.8.6. It should be noted that python 3.8.6 was release on 24 September 2020. It can be possible some dependencies still need time to be compatible with this version (see [here](https://github.com/numpy/numpy/issues/13573#issuecomment-493698760)). My private experience is not to embrace new things too early. 😄 

Anyway, as you have resolved the issue by yourself, I will close it now.
